export const GET_ALL_DOCUMENT = 'GET_ALL_DOCUMENT';
export const GET_ALL_USER_UNASSIGNED = 'GET_ALL_USER_UNASSIGNED';
export const GET_ALL_TRASH_DOCUMENT = 'GET_ALL_TRASH_DOCUMENT';
export const RELOAD_DOCUMENT = 'RELOAD_DOCUMENT';